### ISSUE TITLE
对象类型一节似乎有误

### ISSUE THREAD

**Issue by wenxudong090161** [joye61/typescript-tutorial#1]
您提到

> 注意属性的类型声明之间用分号;，而不是逗号, 。

但是好像定义接口时，属性之间可以用分号 `;` 分隔，也可以用逗号 `,` 分隔，甚至什么都不加也可以。
let man: {
    name: string;
    age: number;
}
let man: {
    name: string,
    age: number,
}
let man: {
    name: string
    age: number
}
以上都是可以的

**Comment by joye61** [comment]
> 您提到
> 
> > 注意属性的类型声明之间用分号;，而不是逗号, 。
> 
> 但是好像定义接口时，属性之间可以用分号 `;` 分隔，也可以用逗号 `,` 分隔，甚至什么都不加也可以。
> let man: {
> name: string;
> age: number;
> }
> let man: {
> name: string,
> age: number,
> }
> let man: {
> name: string
> age: number
> }
> 以上都是可以的


> 您提到
> 
> > 注意属性的类型声明之间用分号;，而不是逗号, 。
> 
> 但是好像定义接口时，属性之间可以用分号 `;` 分隔，也可以用逗号 `,` 分隔，甚至什么都不加也可以。
> let man: {
> name: string;
> age: number;
> }
> let man: {
> name: string,
> age: number,
> }
> let man: {
> name: string
> age: number
> }
> 以上都是可以的

文档已更新，请参考原文，感谢提醒！

**Comment by 123164867376464646** [comment]
交叉使用也是成立，真的抽象😅
