### ISSUE TITLE
接口类型这个名字有点奇怪

### ISSUE THREAD

**Issue by wenxudong090161** [joye61/typescript-tutorial#2]
接口（Interfaces）用来定义对象的类型，但是接口本身不是类型呀

```typescript
// 定义接口类型Person
interface Person {
  name: string;
  age: number;
}
```

这里应该是定义了一个接口Person，而不是定义了接口类型

**Comment by joye61** [comment]
> 接口（Interfaces）用来定义对象的类型，但是接口本身不是类型呀
> 
> ```ts
> // 定义接口类型Person
> interface Person {
>   name: string;
>   age: number;
> }
> ```
> 
> 这里应该是定义了一个接口Person，而不是定义了接口类型

本教程主要面向新手，教程很多内容没有完全按照官方术语来描述！因为接口跟`number` 和 `string` 本质上并没有区别，都是为了描述数据的结构形态，称为**接口类型**会更加便于新手读者理解！作者希望读者在教程中学会这个概念的应用之后，在具体的编码语境中去加深理解这种异同！所以在没有找到更便于理解的描述之前，这个issue就不当作bug处理了。感谢
